### ISSUE TITLE
Unable to launch hs.task process

### ISSUE THREAD

**Issue by Makukuu** [AdamWagner/stackline#117]
I followed the instructions on installing the stackline without success.
The following message is displayed in Hammerspoon console:
`Warning:   LuaSkin: hs.task:launch() Unable to launch hs.task process: launch path not accessible`

Notes: 
1) Firstly, I didn't install in ~/.hammerspoon, but in ~/.config/hammerspoon
Afterwards I uninstalled and performed a clean installation in the according directory.

2) This works for me in regards to getting the `true` output
https://github.com/Hammerspoon/hammerspoon/issues/2930#issuecomment-899092002

But doesn't fix my stackline issue

**Comment by thomascrha** [comment]
Yeah I'm seeing the same issue with that warning and nothing is being rendered

**Comment by Makukuu** [comment]
Yes, I also saw yesterday by chance that the path is different in conf.lua !
But now I'm getting a different problem - do you link it to the executable or to the folder?
`c.paths.yabai                         = '/Users/admin/.config/yabai/yabairc'`
vs
`c.paths.yabai                         = '/Users/admin/.config/yabai'`

In the first case I get the following: 
```
"yabai configuration loaded..\n"
2022-11-24 11:46:57: 11:46:57 ERROR:   LuaSkin: hs.task callback: /Users/admin/.hammerspoon/stackline/stackline/query.lua:19: bad argument #1 to 'for iterator' (table expected, got string)
stack traceback:
	[C]: in function 'next'
	/Users/admin/.hammerspoon/stackline/stackline/query.lua:19: in upvalue 'stackIdMapper'
	/Users/admin/.hammerspoon/stackline/stackline/query.lua:148: in function </Users/admin/.hammerspoon/stackline/stackline/query.lua:147>
	(...tail calls...)
2022-11-24 11:47:00: -- Loading extension: geometry
```

The second case: 
`Warning:   LuaSkin: hs.task:launch() Unable to launch hs.task process: Couldn't posix_spawn: error 13`

I think the problem still lies in the hs install, because even after correcting it with: `hs.ipc.cliInstall('/opt/homebrew/')`
The following happens:
```
> which hs
[string "which hs"]:1: syntax error near 'hs'
```

**Comment by Makukuu** [comment]
Yes!! It was the same issue for me, only I had it installed at two places because of some tutorial I watched.
Working now, Thanks!!
