### ISSUE TITLE
ERROR: module 'stackline.stackline.core' not found:

### ISSUE THREAD

**Issue by johnallen3d** [AdamWagner/stackline#12]
Thanks for this project, love the concept!

I'm giving it a try, and I am getting the following error when launching Hammerspoon.

```
2020-08-03 10:07:53: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2020-08-03 10:07:53: -- Lazy extension loading enabled
2020-08-03 10:07:53: -- Loading ~/.hammerspoon/init.lua
2020-08-03 10:07:53: *** ERROR: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: module 'stackline.stackline.core' not found:
	no field package.preload['stackline.stackline.core']
	no file '/Users/johna/.hammerspoon/stackline/stackline/core.lua'
	no file '/Users/johna/.hammerspoon/stackline/stackline/core/init.lua'
	no file '/Users/johna/.hammerspoon/Spoons/stackline/stackline/core.spoon/init.lua'
	no file '/usr/local/share/lua/5.3/stackline/stackline/core.lua'
	no file '/usr/local/share/lua/5.3/stackline/stackline/core/init.lua'
	no file '/usr/local/lib/lua/5.3/stackline/stackline/core.lua'
	no file '/usr/local/lib/lua/5.3/stackline/stackline/core/init.lua'
	no file './stackline/stackline/core.lua'
	no file './stackline/stackline/core/init.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/stackline/stackline/core.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/stackline/stackline/core/init.lua'
	no file '/Users/johna/.hammerspoon/stackline/stackline/core.so'
	no file '/usr/local/lib/lua/5.3/stackline/stackline/core.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './stackline/stackline/core.so'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/stackline/stackline/core.so'
	no file '/Users/johna/.hammerspoon/stackline.so'
	no file '/usr/local/lib/lua/5.3/stackline.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './stackline.so'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/stackline.so'
stack traceback:
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/johna/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)
```

The only thing that I did differently when getting setup was not cloning to my `~/Downloads` directory and dealing with relative paths (native MacOS version of `ln` does not support the `-r` flag). I cloned to `~/.hammerspoon/src/` instead, so my `~/.hammerspoon` directory looks like this.

```sh
~/.hammerspoon
❯ exa -hla --git
Permissions Size User  Date Modified Name
lrwxr-xr-x    18 johna  3 Aug 10:07  bin -> src/stackline/bin
.rw-r--r--    35 johna  3 Aug  8:49  init.lua
drwxr-xr-x     - johna  3 Aug  8:46  Spoons
drwxr-xr-x     - johna  3 Aug  8:49  src
lrwxr-xr-x    24 johna  3 Aug 10:07  stackline -> src/stackline/stackline
lrwxr-xr-x    20 johna  3 Aug 10:07  utils -> src/stackline/utils
```

and my `init.lua`

```sh
~/.hammerspoon
❯ cat init.lua
require "stackline.stackline.core"
```

Probably something simple I'm missing. I am not (was not) a Hammerspoon user nor do I have Lua experience.

**Comment by alin23** [comment]
@johnallen3d you can do this to make it work:
1. `cd ~/hammerspoon && rm -r bin src stackline utils`
2. `git clone https://github.com/AdamWagner/stackline ~/hammerspoon/stackline`

**Comment by johnallen3d** [comment]
OJ, just so I'm clear, the folder structure should look something like this? If I do this then I no longer see an error launching Hammerspoon (yah!) but I'm not seeing the "pills" when I introduce a stack. 🤔 

```
❯ exa --tree
.
├── init.lua
├── Spoons
├── stackline
│  ├── bin
│  │  └── yabai-get-stacks
│  ├── stackline
│  │  ├── core.lua
│  │  ├── stack.lua
│  │  └── window.lua
│  └── utils
│     ├── flatten.lua
│     ├── table-utils.lua
│     ├── underscore.lua
│     └── utils.lua
```

**Comment by alin23** [comment]
The shell also defaults to `/usr/local/bin/dash` in this which must be installed using `brew install dash`

**Comment by alin23** [comment]
I've fixed most of this stuff here: https://github.com/AdamWagner/stackline/pull/13

But @AdamWagner is already in the middle of a big refactor to ditch the shell script so this might get more stable in the next few days.

**Comment by johnallen3d** [comment]
ah ha! Installing `dash` got me there!
<img width="264" alt="incent-gem — fish 2020-08-03 12-51-08" src="https://user-images.githubusercontent.com/184915/89207003-0850c100-d588-11ea-90bb-c19886b1606d.png">

I'm following the project and will plan to upgrade whn @AdamWagner's PR is merged. 

Thanks for your help!

**Comment by AdamWagner** [comment]
Sorry for the bumpy start @johnallen3d ! I'll update the readme with the tips shared here!

**Comment by johnallen3d** [comment]
Thanks for getting those updated steps out there @AdamWagner and for your help troubleshooting @alin23! I'm looking over the README and trying the latest and two things stand-out.

It looks like the `.` in `.hammerspoon` is missing here:

```
git clone https://github.com/AdamWagner/stackline.git ~/hammerspoon/stackline
```

I don't have a `/usr/local/bin/hs`. I'm guessing that relates to Hammerspoon? I don't have an `hs` on my path at all (`which hs` returns nothing).

Happy to open PR's or help in other ways (continue to be a tester) if I can!

**Comment by johnallen3d** [comment]
OK, I just did `> hs.ipc.cliInstall()` from the Hammerspoon Console...

```sh
❯ which hs
/usr/local/bin/hs
```

🎉

**Comment by alin23** [comment]
> OK, I just did `> hs.ipc.cliInstall()` from the Hammerspoon Console...
> 
> ```shell
> ❯ which hs
> /usr/local/bin/hs
> ```
> 
> 🎉

oh right.. forgot about that. I have that line in my init.lua file, we'll have to add this inside the readme

**Comment by AdamWagner** [comment]
Good catches, @johnallen3d! I fixed the missing "dot" in the hammerspoon path, added instructions for installing `hs`, and added a shout-out to @johnallen3d for identifying these issues & being willing to push though them 👏
