### ISSUE TITLE
Issue enabling stackline

### ISSUE THREAD

**Issue by szfkamil** [AdamWagner/stackline#120]
I followed instructions to the letter, but I have issues enabling it via the command:
```yabai -m window --stack next``` 

I received an error 'could not locate the next managed window.'

Here, I have attached some screenshots. I have yabai working correctly, and I have hamerspoon set up too. I made sure the terminal was next to the browser, also.

<img width="941" alt="CleanShot 2023-03-28 at 18 22 39@2x" src="https://user-images.githubusercontent.com/82778513/228306980-92abc0bd-db96-4b7a-9751-6176a4791c25.png">
![CleanShot 2023-03-28 at 17 47 01@2x](https://user-images.githubusercontent.com/82778513/228307223-f8328da4-17d8-4622-89e4-4b25970fb7e6.png)

I might be missing something simple since I am not experienced with any of this stuff, so I apologize if that is the case and bear that in mind when reviewing the issue.

Thanks,

**Comment by Ronnie76er** [comment]
You did the `hs.ipc.cliInstall("/opt/homebrew")` command correctly **inside** the Hammerspoon console. That installs the command to your operating system.

The cli is meant to be run from on the MacOS terminal. So, you should be able to bring up the `Terminal` command (from Spotlight is probably easiest), and then in there, type `which hs`. That should respond with the path where it thinks that command is, most likely `/opt/homebrew/bin/hs` for you.
