### ISSUE TITLE
How to cycle through stack windows

### ISSUE THREAD

**Issue by babygau** [AdamWagner/stackline#29]
I eventually could use stackline, but how to cycle through stack windows. in yabai bsp mode, I could achieve it through
```
yabai -m query --spaces \
       | jq -re ".[] | select(.visible == 1).index" \
       | xargs -I{} yabai -m query --windows --space {} \
       | jq -sre "add | sort_by(.display, .frame.x, .frame.y, .id) | reverse | nth(index(map(select(.focused == 1))) - 1).id" \
       | xargs -I{} yabai -m window --focus {}
```

**Comment by AdamWagner** [comment]
@babygau Thanks for the comment!

Now that `yabai` has actual stack support, I use:

```sh
# Focus window up/down in stack
ctrl - n : yabai -m window --focus stack.next
ctrl - p : yabai -m window --focus stack.prev
```

**Comment by babygau** [comment]
@AdamWagner thank you for your response, however, what i want to do is to cycle through all windows no matter what they are in bsp nodes or stacks. i find this way is more quicker than that of you have to figure which windows belong to either stack or bsp node
