### ISSUE TITLE
Not really reactive using yabai -m window --insert stack

### ISSUE THREAD

**Issue by danielfalbo** [AdamWagner/stackline#47]
I just installed stackline, I'm not sure if this is really an issue or I am doing something wrong.

In my skhdrc I have
```
ctrl + alt - i : yabai -m window --insert stack
```
, this is the main way I create stacks.

However, looks like hammerspoon does not update the stackline icons until I reload the config.

![in](https://user-images.githubusercontent.com/39460524/97091761-8f20b180-163e-11eb-8ca8-e783ed7ef104.gif)

🤔

**Comment by AdamWagner** [comment]
@danielfalbo first, sorry for the slow response (have been taking stackline apart and putting it back together again in pursuit of testability). 

I was about to upload a GIF demonstrating that stackline _does_ update when `yabai -m window --insert stack` is executed and a new window is created…

… but during the "official take", it _didn't_ work. So, at least I'm able to reproduce. For me, it's variable (sometimes it works, sometimes it doesn't.

It's clear to me that it's less consistent than creating a new window and _then_ executing `yabai -m window south --stack  $WIN_ID`). I'm not sure _why_ yet, but will look into it.

**Comment by AdamWagner** [comment]
@danielfalbo unfortunately, I'm no longer able to reproduce this. I tried many different configurations, including traditionally "difficult" apps such as iTerm2 that constrain window size in discrete steps. See attached gif:

![Screenshot 2020-11-28 at 16 23 41](https://user-images.githubusercontent.com/1683979/100528895-8b7ccf00-3196-11eb-8539-72719c4d61dd.gif)

Have you continued to observe that stackline doesn't update correctly when windows are directly inserted? If so, do you notice anything different about what I'm doing in the screen recording (activating insert mode with an `skhd` keybind, then typing `cmd+n` to create a new window for the active app, or launching a new app with Alfred) that could explain why I'm not able to reproduce the issue?

Thanks for the help!

**Comment by danielfalbo** [comment]
With Big Sur now works fine on my machine too : ) Sometimes yabai freezes with no reason but that's a yabai issue, not a Stackline issue. Thank you for your time : )

**Comment by danielfalbo** [comment]
By the way, beautiful `ls` tool! What do you use?

**Comment by AdamWagner** [comment]
@danielfalbo I use [lsd](https://github.com/Peltoche/lsd) - `brew install lsd`.

Specifically I use this options: `  lsd --long --human-readable --timesort --almost-all --group-dirs first --blocks size,date,name --date relative --size short --color always`

```fish
function ls --description 'Custom ls'
  # TODO: Why is this required?
  # call ls to set $LS_COLORS
  tput rmam # disable line wrapping
  lsd --long --human-readable --timesort --almost-all --group-dirs first --blocks size,date,name --date relative --size short --color always $argv;
  tput smam # enable line wrapping
end
```

**Comment by danielfalbo** [comment]
Thank you : )
