### ISSUE TITLE
Documentation for setup

### ISSUE THREAD

**Issue by jasonpott** [AdamWagner/stackline#52]
relates to this section: https://github.com/AdamWagner/stackline#2-install-the-hammerspoon-cli-tool

In this section of the documentation I think it could be clearer about what actions are required. When reading this it wasn't immediately clear that I needed to open the hammerspoon.app and then run the hs.cliInstall() there. 

Then when figured out that I was supposed to be in Hammerspoon I was then trying to run the "which" command when this needs to be run back in the console.

I think some of this confusion is down to my introductory level knowledge of bash and never having used hammerspoon before but if other novices are looking to make use of this software they may similarly be confused.

**Comment by AdamWagner** [comment]
Thanks @jasonpott !

The phenomenon you're describing is one of the most frustrating aspects about trying to follow "how-tos" on Github or around the internet – there's almost always a couple of things that the author takes for granted :/ I'm sorry to have contributed to this.

Do you think this is better?
https://github.com/AdamWagner/stackline#2-install-the-hammerspoon-cli-tool

**Comment by jasonpott** [comment]
@AdamWagner happy to be able to contribute.

That is much better and the screen shots really help.

The one step I can't see within the documentation is whether hammerspoon needed to be explicitly opened or whether the setup process initiallised it. 

Perhaps the bash code 
```
# Launch hammerspoon (or make sure it's running)
open -a "Hammerspoon"
``` 
Should replace "Ensure Hammerspoon is running" ?

**Comment by AdamWagner** [comment]
@jasonpott Great to hear! 

I updated the shell comment in the readme per your suggestion 😉
