### ISSUE TITLE
Any reason not to deprecate support for ipc messages?

### ISSUE THREAD

**Issue by AdamWagner** [AdamWagner/stackline#53]
The pattern below is repeated throughout the documentation:

>Config values can be set using the `hs` CLI:
>   `hs -c "stackline.config:set('appearance.radius', 3)"`
>… or the ipc port:
>   `echo ":appearance.radius:3` | hs -m stackline-config`

Both of these commands have the same effect – setting the `apperance.radius` to `3`.

### Benefit (?)
To my knowledge, the ipc port approach offers no real advantage.

The ipc port approach …

- does not require less setup or fewer dependencies
- does not offer more functionality
- is not more or less flexible
- is not easier to understand

…than the `hs` CLI.

The _only_ benefit I can think of is inertia; if some folks are already used to the ipc approach, or get/set config values in their `yabairc` using ipc (I doubt there are any/many), then I understand that it's preferable to not have to change these.

### Cost

Support for the ipc approach accounts for more than 20% of lines in `configmanager.lua`.

Also, since it must _parse strings_, it is substantially more complicated than calling `stackline.config:set(…)` or `stackline.config:toggle(…)`.

The ipc approach requires registering a local port and is not idempotent. This caused [stackline to crash for at least one user](https://github.com/AdamWagner/stackline/issues/46#issuecomment-723527826) (before a [guard was added](https://github.com/AdamWagner/stackline/commit/e85c57cb7ab9df5fb0a24957c7aa6a525f13fe78) to prevent initializing stackline more than once).

Finally, supporting 2 (similar) ways to accomplish the same thing unnecessarily complicates the documentation.

---

So, if there are good reasons not to deprecate support for modifying config values via ipc… I'm not aware of them.

Does anyone feel strongly that modifying stackline config values via ipc should _not_ be deprecated?

**Comment by AdamWagner** [comment]
@alin23 – curious to see if you think there's any reason to use ipc over the `hs` CLI directly?

**Comment by alin23** [comment]
@AdamWagner Having two ways to do one thing is usually just adding confusion. Deprecating IPC support is a good idea 👌

**Comment by AdamWagner** [comment]
Thanks a lot ya'll! 
Since this has been open for two weeks without a single plea for keeping IPC support around… it seems safe to remove it and update the docs 😌️ … which I can probably complete in the next couple of weeks.
