### ISSUE TITLE
Stackline uses hardcoded path to yabai and jq in yabai-get-stack-idx

### ISSUE THREAD

**Issue by shepherdjerred** [AdamWagner/stackline#55]
`/bin/yabai-get-stack-idx` uses a hardcoded path to jq and yabai. This is an issue on M1 Macs since Homebrew executables for ARM Macs are stored in a different location than x86 Macs.

Stackline failed to work properly on my M1 Mac Mini until this line was changed to the proper path (i.e. /opt/homebrew/bin/yabai).

https://github.com/AdamWagner/stackline/blob/9d9619974ee32abe84b674614ad22760b0b801ba/bin/yabai-get-stack-idx#L3-L4

**Comment by shepherdjerred** [comment]
I don't know LUA, but I was able to make a patch. I'll submit a PR in a bit.

**Comment by shepherdjerred** [comment]
https://github.com/AdamWagner/stackline/pull/56

**Comment by AdamWagner** [comment]
@shepherdjerred awesome job fixing this! 

Really clever to pass the paths to the script itself. I thought you might call out to the `hs` CLI in the script itself (`hs -c "stackline.config:get('paths.yabai')"`), but your approach is much simpler/nicer. 👍 Will merge!

**Comment by jacktuck** [comment]
For those who use M1 and Intel Macs

```
brew_prefix = string.gsub(hs.execute("brew --prefix", true), '[\r\n]+', '')
stackline.config:set('paths.yabai', brew_prefix  .. "/bin/yabai")
```

seems to work
