### ISSUE TITLE
Stackline is not working

### ISSUE THREAD

**Issue by yevhenshymotiuk** [AdamWagner/stackline#61]
I can't see a stackline after launching Hammerspoon and stacking windows

`~/.hammerspoon`:
```
.hammerspoon
├── Spoons
├── stackline
│  ├── bin
│  │  └── yabai-get-stack-idx
│  ├── lib
│  │  ├── debug.lua
│  │  ├── json.lua
│  │  ├── utils.lua
│  │  └── valid.lua
│  ├── stackline
│  │  ├── configmanager.lua
│  │  ├── query.lua
│  │  ├── stack.lua
│  │  ├── stackline.lua
│  │  ├── stackmanager.lua
│  │  └── window.lua
│  ├── conf.lua
│  └── README.md
└── init.lua
```

`~/.hammerspoon/init.lua`: 
```
stackline = require "stackline.stackline.stackline"
stackline:init()
```

Mac OS 11.2

**Comment by kpritam** [comment]
I am having the same issue with Big Sur.

**Comment by kpritam** [comment]
Issue for me was `jq` path. After providing custom path in `init.lua` like below, icons started appearing:
```
stackline = require "stackline.stackline.stackline"
local stacklineConfig = {
     paths.jq = '/Users/pritamkadam/.nix-profile/bin/jq'
 }
stackline:init(stacklineConfig)
```

**Comment by yevhenshymotiuk** [comment]
`*** ERROR: /Users/yevhenshymotiuk/.hammerspoon/init.lua:3: '}' expected (to close '{' at line 2) near '='` if using your `init.lua`

**Comment by kpritam** [comment]
can you just try this:
```lua
stackline = require "stackline.stackline.stackline"
local stacklineConfig = {
    paths = {
        jq = '/YourUserName/.nix-profile/bin/jq'
    },
}
stackline:init(stacklineConfig)
```

**Comment by yevhenshymotiuk** [comment]
Yea, it works now, thanks, but you missed `/Users` before `/YourUserName/.nix-profile/bin/jq`. Can you explain, what was the issue with brackets?

**Comment by yevhenshymotiuk** [comment]
I'm closing this for now. It might be better to add some more information about this case to wiki, but it is not a bug

**Comment by AdamWagner** [comment]
Note for folks who may stumble upon this in the future: `jq` is no longer a dependency.
