### ISSUE TITLE
Icons don't change when toggling showIcons 

### ISSUE THREAD

**Issue by acdifran** [AdamWagner/stackline#68]
When I toggle showIcons (both via terminal and hs console) the icons don't change. However, as soon as I move a window, or perform a similar action, the icons will update. So it seems that while the config is updated, the icons don't actually change until some update event is performed. Is this by design? If so, is there a command I can run to refresh the icons?

I saw you mention something similar here: https://github.com/AdamWagner/stackline/issues/5, but this is closed, so not sure if it's the same issue or something else.

Thanks for the awesome tool!

**Comment by AdamWagner** [comment]
hi @acdifran!
Apologies for the slow response.
I think I've fixed this. Let me know if you still see the issue using the latest version (main branch).

> Is this by design?

No. There are onChange events associated with config keys in [configmanager.lua](https://github.com/AdamWagner/stackline/blob/master/stackline/configmanager.lua#L60). These are intended to fire when the corresponding keys are set/updated. 

I had accidentally nested the change event for any `appearance` related setting in a table.

Correct
>     appearance = function() stackline.manager:resetAllIndicators() end,

Incorrect

>     appearance = { onChange = function() stackline.manager:resetAllIndicators() end },

**Comment by acdifran** [comment]
@AdamWagner I pulled the latest branch and unfortunately I'm now hitting this same issue here: https://github.com/AdamWagner/stackline/issues/76

**Comment by AdamWagner** [comment]
@acdifran Sorry about that. 

The problem in #76 is straightforward.
And although I'm not sure why it works for me, but not others, I consolidated global variables at the top of the main file, which should either fix this or more clearly reveal a deeper issue. 

Please pull the latest once more and let me know if it works now? 🤞️ Thanks.

**Comment by acdifran** [comment]
@AdamWagner everything is working now, thanks!

**Comment by AdamWagner** [comment]
Great to hear, thanks a ton for for reporting back!
