### ISSUE TITLE
Undo stack window

### ISSUE THREAD

**Issue by blackvvine** [AdamWagner/stackline#70]
Hi,

I've recently switched from i3wm on Linux to yabai+stackline+skhd, so I'm kind of new to this. I have configured a keybinding to stack a window with the next one via:

```bash
yabai -m window --stack next
```

However, I can't seem to find any docs on how this can be undone i.e. how can I "unstack" windows.

**Comment by johnallen3d** [comment]
I have a little script I use to "toggle" stacks (can't remember if I copied this from someone else at this point).

```sh
#! /usr/bin/env bash

current_layout="$(yabai -m query --spaces --space | jq -re .type)"

target_layout="bsp"

[ "${current_layout}" = "bsp" ] && target_layout="stack"

yabai -m space --layout $target_layout
```

This is triggered in my `skhd` config via:

```sh
cmd - m : /Users/usernamehere/.config/yabai/toggle-monocle
```

**Comment by blackvvine** [comment]
Awesome, thank you 🎉 🙏

**Comment by kiryph** [comment]
Here is a one-liner for `~/.config/skhd/skhdrc`

```sh
alt - t : yabai -m space --layout $( [ "$(yabai -m query --spaces --space | jq -re .type)" = 'bsp' ] && echo 'stack' || echo 'bsp' )
```
