### ISSUE TITLE
Cannot get hs cli

### ISSUE THREAD

**Issue by BR00l** [AdamWagner/stackline#83]
> hs.ipc.cliInstall()
2021-06-15 21:56:36: -- Loading extension: ipc
false

thats all im getting, and i cannot move any further sadly.
Im not a lua fluent person, so excuse me about my (maybe) silly problem.

**Comment by z20240** [comment]
I have the same issue.

**Comment by z20240** [comment]
I think it the hammerspoon issue
I raise the issue to there and the developers gave me advice. 

Reference: [Cannot get hs.ipc.cli](https://github.com/Hammerspoon/hammerspoon/issues/2930)
